# Generated by Django 4.2.7 on 2023-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arXiv',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('submitter', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.TextField()),
                ('title', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('journal_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('report_no', models.CharField(blank=True, max_length=100, null=True)),
                ('categories', models.CharField(max_length=255)),
                ('license', models.URLField(blank=True, null=True)),
                ('abstract', models.TextField()),
                ('versions', models.JSONField()),
                ('update_date', models.DateField()),
                ('authors_parsed', models.JSONField()),
            ],
        ),
    ]
